/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PixoStencilButton {
    }
}
declare global {
    interface HTMLPixoStencilButtonElement extends Components.PixoStencilButton, HTMLStencilElement {
    }
    var HTMLPixoStencilButtonElement: {
        prototype: HTMLPixoStencilButtonElement;
        new (): HTMLPixoStencilButtonElement;
    };
    interface HTMLElementTagNameMap {
        "pixo-stencil-button": HTMLPixoStencilButtonElement;
    }
}
declare namespace LocalJSX {
    interface PixoStencilButton {
    }
    interface IntrinsicElements {
        "pixo-stencil-button": PixoStencilButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pixo-stencil-button": LocalJSX.PixoStencilButton & JSXBase.HTMLAttributes<HTMLPixoStencilButtonElement>;
        }
    }
}
